# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Census
                                 A QGIS plugin
 Ce plugin permet de définir un parcours optimal sur une zone définie par l'utilisateur dasn un contexte de recensement dans des zones où les données sont moindres
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-16
        copyright            : (C) 2023 by Victorien OLLIVIER
        email                : victorien.ollivier@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Census class from file Census.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Census import Census
    return Census(iface)
